### ISSUE TITLE
More robustly handle uploading job outputs

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_tso500#19]
Job outputs are uploaded in parallel and associated to the job output spec with `dx-jobutil-add-output` here: https://github.com/eastgenomics/eggd_tso500/blob/ae5633715754453ea8c001cc5b5f38434679330e/src/code.sh#L526

which is calling this function: https://github.com/eastgenomics/eggd_tso500/blob/ae5633715754453ea8c001cc5b5f38434679330e/src/code.sh#L328-L353

This might not be totally robust due to a failed job here on reading the `job_output.json` in `dx-jobutil-add-output`: https://platform.dnanexus.com/panx/projects/GfxjY2j4k7Qq1Q0QgVZ9Kxvg/monitor/job/GfxjY3Q4k7QfZVGvB380xjZ0

```
Traceback (most recent call last):
  File "/usr/local/bin/dx-jobutil-add-output", line 180, in <module>
    output_file.write(update_output_json(output_json))
  File "/usr/local/bin/dx-jobutil-add-output", line 154, in update_output_json
    output_spec = json.loads(output_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

If this happens again, probably should drop the linking from this function and capture all the uploaded file IDs, then associate these to the appropriate output spec field in one call

**Comment by jethror1** [comment]
could probably also put in an flock before the `dx-jobutil-add-output` to handle concurrency issue

**Comment by jethror1** [comment]
after further investigating this issue could come from the fact that the `job_output.json` file does not exist when the app starts, when calling `dx-jobutil-add-output` it checks if the file exists and if not, will create an empty file from the `os.open()` call on line 172. It then will try place an flock on the file and write the output in json format to the empty file (line 185). If another processes checks for existence of the file once it has been created and acquires the flock before the original process does (line 177), it will expect the file to be in a valid json format and calls `json.loads()` from the `update_output_json()` function, which then raises the error we have seen above.

We can show this error is raised on an empty file as would happen with the following:
```
>>> os.open('job_output.json', os.O_WRONLY | os.O_CREAT | os.O_EXCL)
3
>>> with open('job_output.json') as fh:
...     contents = fh.read()
...     json.loads(contents)
... 
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Relevant dx-toolkit code for this:
https://github.com/dnanexus/dx-toolkit/blob/master/src/python/scripts/dx-jobutil-add-output#L168-L187

An easy fix for this would be to just create a valid JSON file on the app starting with something like `echo "{}" > job_output.json`

**Comment by jethror1** [comment]
This can be further tested to show that this is the issue by making a minimal Python script to simulate what `dx-jobutil-add-output` is doing by trying to get an flock on the file and reading it in with `json.loads`:

```
from contextlib import contextmanager
import fcntl
import json
import os

@contextmanager
def flock(fd):
    fcntl.flock(fd, fcntl.LOCK_EX)
    try:
        yield
    finally:
        fcntl.flock(fd, fcntl.LOCK_UN)


def update_output_json(output_json):
    output_spec = json.loads(output_json)

    return json.dumps(output_spec, indent=4) + "\n"


try:
    # Atomically test for file existence and create it if it doesn't
    # exist. Below we branch on whether the file existed or not at the time
    # that this was tried.
    output_fd = os.open('job_output.json', os.O_WRONLY | os.O_CREAT | os.O_EXCL)
except OSError as e:
    # File exists, but we don't have a handle to it yet. Open it and lock for
    # exclusive use
    with open('job_output.json', 'r+') as output_file:
        with flock(output_file):
            output_json = output_file.read()
            output_file.seek(0)
            output_file.write(update_output_json(output_json))
            output_file.truncate()
else:
    # File didn't exist before; we now have an FD on it. Lock it for exclusive
    # use
    with os.fdopen(output_fd, 'w') as output_file:
        with flock(output_file):
            output_file.write(update_output_json("{}"))
``` 

If we then create a loop to call this in parallel it will show that we can force the same error:

```
$ for x in $(seq 1 100); do rm job_output.json; seq 1 2 | xargs -n1 -P2 -I{} sh -c "python3 ~/Projects/small_things/test_dx_jobutil_a
dd_output_parallel.py"; done

Traceback (most recent call last):
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 36, in <module>
    output_file.write(update_output_json(output_json))
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 19, in update_output_json
    output_spec = json.loads(output_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 36, in <module>
    output_file.write(update_output_json(output_json))
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 19, in update_output_json
    output_spec = json.loads(output_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 36, in <module>
    output_file.write(update_output_json(output_json))
  File "/home/jethro/Projects/small_things/test_dx_jobutil_add_output_parallel.py", line 19, in update_output_json
    output_spec = json.loads(output_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

As can be seen, in running this 100 times we raise the same error 3 times.

If `job_output.json` already exists, we can show this error is never raised by the running the above 1000 times:
```
$ touch job_output.json
$ for x in $(seq 1 1000); do seq 1 2 | xargs -n1 -P2 -I{} sh -c "python3 ~/Projects/small_things/test_dx_jobutil_add_output_parallel.
py"; done
$ 
```
